@PhotoSharingApplication.CommentsApi_HostAddress = http://localhost:5161

GET {{PhotoSharingApplication.CommentsApi_HostAddress}}/api/photos/1/comments

###

GET {{PhotoSharingApplication.CommentsApi_HostAddress}}/api/comments/8

###

POST {{PhotoSharingApplication.CommentsApi_HostAddress}}/api/comments
Content-Type: application/json

{
"id": 0,
"photoId": 1,
"subject": "New Comment",
"body": "Added through .http file"
}

###

PUT {{PhotoSharingApplication.CommentsApi_HostAddress}}/api/comments/8
Content-Type: application/json

{
    "id": 8,
    "photoId": 1,
    "subject": "New Comment",
    "body": "Modified through .http file"
}

###

DELETE {{PhotoSharingApplication.CommentsApi_HostAddress}}/api/comments/8

###
